# Generated by Django 2.2.17 on 2020-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201204_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
