# Generated by Django 2.2.17 on 2020-12-05 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20201204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='likes',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
